### ISSUE TITLE
updates.ForEach is not a function

### ISSUE THREAD

**Issue by dcparga** [yagop/node-telegram-bot-api#284]
> Bug Report

I have read:

* [Usage information](https://github.com/yagop/node-telegram-bot-api/tree/master/doc/usage.md)
* [Help information](https://github.com/yagop/node-telegram-bot-api/tree/master/doc/help.md)

I am using the latest version of the library.

### Expected Behavior

The process should be able to run without problem and indefinitely without throwing an error.

### Actual Behavior

After the whole day running without problems, around 9pm my process start to throw this message continuously:

Unhandled rejection TypeError: updates.forEach is not a function
at _lastRequest._getUpdates.then.updates (/app/node_modules/node-telegram-bot-api/src/telegramPolling.js:102:17)
at tryCatcher (/app/node_modules/bluebird/js/release/util.js:16:23)
at Promise._settlePromiseFromHandler (/app/node_modules/bluebird/js/release/promise.js:510:31)
at Promise._settlePromise (/app/node_modules/bluebird/js/release/promise.js:567:18)
at Promise._settlePromise0 (/app/node_modules/bluebird/js/release/promise.js:612:10)
at Promise._settlePromises (/app/node_modules/bluebird/js/release/promise.js:691:18)
at Async._drainQueue (/app/node_modules/bluebird/js/release/async.js:133:16)
at Async._drainQueues (/app/node_modules/bluebird/js/release/async.js:143:10)
at Immediate.Async.drainQueues (/app/node_modules/bluebird/js/release/async.js:17:14)
at runCallback (timers.js:649:20)
at tryOnImmediate (timers.js:622:5)
at processImmediate [as _immediateCallback] (timers.js:594:5)

**Comment by GochoMugo** [comment]
Are you able to reproduce the bug?

**Comment by dcparga** [comment]
Not in an easy way. I'm not sure why it happens. The only thing I know it happened to me twice, both of them at almost the same time on two conseqcutives days (around 9pm CET).

I'm not sure, but I think is the same error that appears when you have more than one instance of the bot running.

**Comment by GochoMugo** [comment]
If you want to run multiple instances of the application, please use [WebHooks](https://github.com/yagop/node-telegram-bot-api/blob/master/doc/usage.md#webhooks). Using polling is **not** scalable. See more [help information](https://github.com/yagop/node-telegram-bot-api/blob/master/doc/help.md#scalable) on scaling (Sorry! Help information is a bit incomplete! We really need help in that area.).

Otherwise, it will be hard for us to fix the bug (comfortably) if we can **not** pinpoint why and how it occurs. We need to investigate more on this.

**Comment by dcparga** [comment]
Gocho, maybe I have explained myself wrong. The thing is that **I don't want to run multiple instances** of my bot, only one. But I think that the error that appears is the same as if I run more than one. I just said that to see if it could help to understand better the error.

I'll try to give more information if I'm able to get a better understading of the error. I just wanted to see if someone could bring some light on the cause of the error. 

BTW, I'm going to try the webhook, just to see if the behaviour improves and errors are avoided.

**Comment by lokhmakov** [comment]
This simple script:

```
import TelegramBot from 'node-telegram-bot-api'

const token = `...`

const bot = new TelegramBot(token, { polling: true })
```

Result:

```
Unhandled rejection TypeError: updates.forEach is not a function
at _lastRequest._getUpdates.then.updates (PROJECT_DIR/node_modules/node-telegram-bot-api/src/telegramPolling.js:102:17)
at tryCatcher (PROJECT_DIR/node_modules/bluebird/js/release/util.js:16:23)
at Promise._settlePromiseFromHandler (PROJECT_DIR/node_modules/bluebird/js/release/promise.js:510:31)
at Promise._settlePromise (PROJECT_DIR/node_modules/bluebird/js/release/promise.js:567:18)
at Promise._settlePromise0 (PROJECT_DIR/node_modules/bluebird/js/release/promise.js:612:10)
at Promise._settlePromises (PROJECT_DIR/node_modules/bluebird/js/release/promise.js:691:18)
at Async._drainQueue (PROJECT_DIR/node_modules/bluebird/js/release/async.js:133:16)
at Async._drainQueues (PROJECT_DIR/node_modules/bluebird/js/release/async.js:143:10)
at Immediate.Async.drainQueues (PROJECT_DIR/node_modules/bluebird/js/release/async.js:17:14)
at runCallback (timers.js:651:20)
at tryOnImmediate (timers.js:624:5)
at processImmediate [as _immediateCallback] (timers.js:596:5)
```

**Comment by lokhmakov** [comment]
`telegramPolling.js:102` updates return boolean true not array

**Comment by mjanssen** [comment]
Having the same issue after updating to 0.26.
The _getUpdates() function is returning a bool instead of an useable array. No clue why...
I also noticed the `setWebHook` request is called every time it's polling as well, even though I'm not using a webook.

**Comment by lokhmakov** [comment]
Stack trace upper:

`src/telegram.js:172`

data is

`
{ ok: true,
  result: true,
  description: 'Webhook is already deleted' }
`

**Comment by mjanssen** [comment]
Seems to be working fine now. Didn't change anything 🤔

**Comment by dcparga** [comment]
I've been using the polling option for a whole day whitout problems, it just started to fail suddenly, my app crashed, and after rebooting it, it worked again like a charm. That make me thing that it could be something related with Telegram servers, but I cannot assure it. Is just a intuition.

**Comment by lokhmakov** [comment]
I think something wrong with logic of enable polling. Polling wait array of polling results but get in result boolean. May be telegram servers automatically delete webHook and no need to call it manually

**Comment by lokhmakov** [comment]
Try to change polling and return if result data not array

**Comment by lokhmakov** [comment]
Change `src/telegramPolling:97` to:

```
  _polling() {
    this._lastRequest = this
      ._getUpdates()
      .then(updates => {
        if (!(!!updates && Array === updates.constructor)) return
        this._lastUpdate = Date.now();
        debug('polling data %j', updates);
        updates.forEach(update => {
```

And all works good.

**Comment by GochoMugo** [comment]
Just pushed a fix for this in commit [130f6940ceb9972a7b0ac0636ac16e7e53984a46](https://github.com/yagop/node-telegram-bot-api/commit/130f6940ceb9972a7b0ac0636ac16e7e53984a46) (see how to reproduce the bug, and how we have fixed it!). Please try it out and let us know of the results.

**Comment by lokhmakov** [comment]
Console repeat this:

```
{ Error: ETELEGRAM: 409 Conflict: terminated by other long poll or webhook
    at request.then.resp (PROJECT_DIR/node_modules/node-telegram-bot-api/src/telegram.js:181:15)
    at tryCatcher (PROJECT_DIR/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (PROJECT_DIR/node_modules/bluebird/js/release/promise.js:510:31)
    at Promise._settlePromise (PROJECT_DIR/node_modules/bluebird/js/release/promise.js:567:18)
    at Promise._settlePromise0 (PROJECT_DIR/node_modules/bluebird/js/release/promise.js:612:10)
    at Promise._settlePromises (PROJECT_DIR/node_modules/bluebird/js/release/promise.js:691:18)
    at Async._drainQueue (PROJECT_DIR/node_modules/bluebird/js/release/async.js:133:16)
    at Async._drainQueues (PROJECT_DIR/node_modules/bluebird/js/release/async.js:143:10)
    at Immediate.Async.drainQueues (PROJECT_DIR/node_modules/bluebird/js/release/async.js:17:14)
    at runCallback (timers.js:651:20)
    at tryOnImmediate (timers.js:624:5)
    at processImmediate [as _immediateCallback] (timers.js:596:5)
  code: 'ETELEGRAM',
  response: 
   IncomingMessage {
     _readableState: 
      ReadableState {
        objectMode: false,
        highWaterMark: 16384,
        buffer: [Object],
        length: 0,
        pipes: null,
        pipesCount: 0,
        flowing: true,
        ended: true,
...
```

**Comment by GochoMugo** [comment]
Do you have other instances of your bot running?

**Comment by lokhmakov** [comment]
Created new bot. All works fine. 10x

**Comment by GochoMugo** [comment]
Fixed in **v0.27.0**.

Thanks @dcparga, @lokhmakov and @mjanssen for your time and effort in fixing this bug.
